//
// Created by xilef on 9/22/2025.
//

#ifndef MAZEPROJECTSHERBROOKES1_ENTRYPOINTCARDUINO_H
#define MAZEPROJECTSHERBROOKES1_ENTRYPOINTCARDUINO_H

void SetupMaze();

void LoopMaze();

#endif //MAZEPROJECTSHERBROOKES1_ENTRYPOINTCARDUINO_H